/** tokens.css :root / .dark 시맨틱 → 원시 토큰 매핑 (정본) */
const LIGHT: Record<string, string> = {
  "--canvas": "white",
  "--background": "white",
  "--foreground": "grayscale-140",
  "--card": "white",
  "--card-foreground": "grayscale-140",
  "--background-muted": "grayscale-10",
  "--background-muted-foreground": "grayscale-140",
  "--card-muted": "grayscale-10",
  "--card-muted-foreground": "grayscale-140",
  "--popover": "white",
  "--popover-foreground": "grayscale-140",
  "--inverse": "grayscale-140",
  "--inverse-foreground": "white",
  "--foreground-muted": "grayscale-110",
  "--foreground-placeholder": "grayscale-70",
  "--foreground-disabled": "grayscale-60",
  "--primary": "brand-500",
  "--primary-foreground": "white",
  "--primary-container": "brand-100",
  "--primary-container-foreground": "brand-500",
  "--secondary": "grayscale-15",
  "--secondary-foreground": "grayscale-140",
  "--secondary-container": "grayscale-110",
  "--secondary-container-foreground": "white",
  "--muted": "grayscale-15",
  "--muted-foreground": "grayscale-90",
  "--accent": "brand-50",
  "--accent-foreground": "brand-600",
  "--destructive": "error-500",
  "--destructive-foreground": "white",
  "--destructive-container": "error-100",
  "--destructive-container-foreground": "error-600",
  "--dim-10": "black-opacity-10",
  "--dim-20": "black-opacity-60",
  "--dim-30": "black-opacity-80",
  "--dim-40": "black-opacity-90",
  "--divider": "grayscale-15",
  "--divider-strong": "grayscale-30",
  "--border-strong": "grayscale-140",
  "--border-inverse": "white",
  "--success": "success-500",
  "--success-foreground": "white",
  "--warning": "warning-500",
  "--warning-foreground": "grayscale-140",
  "--info": "info-500",
  "--info-foreground": "white",
  "--border": "grayscale-20",
  "--input": "grayscale-30",
  "--disabled": "grayscale-15",
  "--disabled-foreground": "grayscale-60",
  "--disabled-border": "grayscale-20",
  "--ring": "brand-500",
  "--chart-1": "brand-500",
  "--chart-2": "brand-400",
  "--chart-3": "brand-600",
  "--chart-4": "brand-300",
  "--chart-5": "brand-700",
  "--sidebar": "white",
  "--sidebar-foreground": "grayscale-140",
  "--sidebar-primary": "brand-500",
  "--sidebar-primary-foreground": "white",
  "--sidebar-accent": "brand-50",
  "--sidebar-accent-foreground": "brand-600",
  "--sidebar-border": "grayscale-20",
  "--sidebar-ring": "brand-500",
}

const DARK: Record<string, string> = {
  "--canvas": "black",
  "--background": "grayscale-140",
  "--foreground": "grayscale-10",
  "--card": "grayscale-140",
  "--card-foreground": "grayscale-10",
  "--background-muted": "grayscale-130",
  "--background-muted-foreground": "grayscale-10",
  "--card-muted": "grayscale-130",
  "--card-muted-foreground": "grayscale-10",
  "--popover": "grayscale-140",
  "--popover-foreground": "grayscale-10",
  "--inverse": "grayscale-10",
  "--inverse-foreground": "grayscale-140",
  "--foreground-muted": "grayscale-40",
  "--foreground-placeholder": "grayscale-80",
  "--foreground-disabled": "grayscale-70",
  "--primary": "brand-500",
  "--primary-foreground": "white",
  "--primary-container": "brand-800",
  "--primary-container-foreground": "brand-100",
  "--secondary": "grayscale-130",
  "--secondary-foreground": "grayscale-10",
  "--secondary-container": "grayscale-130",
  "--secondary-container-foreground": "white",
  "--muted": "grayscale-130",
  "--muted-foreground": "grayscale-70",
  "--accent": "brand-800",
  "--accent-foreground": "brand-100",
  "--destructive": "error-400",
  "--destructive-foreground": "white",
  "--destructive-container": "error-800",
  "--destructive-container-foreground": "error-100",
  "--dim-10": "black-opacity-10",
  "--dim-20": "black-opacity-60",
  "--dim-30": "black-opacity-80",
  "--dim-40": "black-opacity-90",
  "--divider": "grayscale-130",
  "--divider-strong": "grayscale-110",
  "--border-strong": "grayscale-10",
  "--border-inverse": "grayscale-140",
  "--success": "success-400",
  "--success-foreground": "white",
  "--warning": "warning-400",
  "--warning-foreground": "grayscale-140",
  "--info": "info-400",
  "--info-foreground": "white",
  "--border": "grayscale-130",
  "--input": "grayscale-110",
  "--disabled": "grayscale-120",
  "--disabled-foreground": "grayscale-70",
  "--disabled-border": "grayscale-110",
  "--ring": "brand-400",
  "--chart-1": "brand-400",
  "--chart-2": "brand-500",
  "--chart-3": "brand-300",
  "--chart-4": "brand-600",
  "--chart-5": "brand-200",
  "--sidebar": "grayscale-140",
  "--sidebar-foreground": "grayscale-10",
  "--sidebar-primary": "brand-500",
  "--sidebar-primary-foreground": "white",
  "--sidebar-accent": "brand-800",
  "--sidebar-accent-foreground": "brand-100",
  "--sidebar-border": "grayscale-110",
  "--sidebar-ring": "brand-400",
}

export function getSemanticTokenSource(
  variable: string,
  theme: "light" | "dark"
): string {
  const map = theme === "dark" ? DARK : LIGHT
  const source = map[variable]
  if (!source) return "—"
  return source
}
