/** tokens.css :root / .dark 시맨틱 → 원시 토큰 매핑 (정본) */
const LIGHT: Record<string, string> = {
  "--canvas": "white",
  "--background": "white",
  "--foreground": "grayscale-140",
  "--card": "white",
  "--card-foreground": "grayscale-140",
  "--popover": "white",
  "--popover-foreground": "grayscale-140",
  "--primary": "brand-500",
  "--primary-foreground": "white",
  "--secondary": "grayscale-15",
  "--secondary-foreground": "grayscale-140",
  "--muted": "grayscale-15",
  "--muted-foreground": "grayscale-90",
  "--accent": "brand-50",
  "--accent-foreground": "brand-600",
  "--destructive": "error-500",
  "--destructive-foreground": "white",
  "--success": "success-500",
  "--success-foreground": "white",
  "--warning": "warning-500",
  "--warning-foreground": "grayscale-140",
  "--info": "info-500",
  "--info-foreground": "white",
  "--border": "grayscale-20",
  "--input": "grayscale-30",
  "--disabled": "grayscale-15",
  "--disabled-foreground": "grayscale-60",
  "--disabled-border": "grayscale-40",
  "--ring": "brand-500",
  "--chart-1": "oklch(0.809 0.105 251.813)",
  "--chart-2": "oklch(0.623 0.214 259.815)",
  "--chart-3": "oklch(0.546 0.245 262.881)",
  "--chart-4": "oklch(0.488 0.243 264.376)",
  "--chart-5": "oklch(0.424 0.199 265.638)",
  "--sidebar": "white",
  "--sidebar-foreground": "grayscale-140",
  "--sidebar-primary": "brand-500",
  "--sidebar-primary-foreground": "white",
  "--sidebar-accent": "brand-50",
  "--sidebar-accent-foreground": "brand-600",
  "--sidebar-border": "grayscale-20",
  "--sidebar-ring": "brand-500",
}

const DARK: Record<string, string> = {
  "--canvas": "grayscale-140",
  "--background": "grayscale-140",
  "--foreground": "grayscale-10",
  "--card": "grayscale-130",
  "--card-foreground": "grayscale-10",
  "--popover": "grayscale-130",
  "--popover-foreground": "grayscale-10",
  "--primary": "brand-500",
  "--primary-foreground": "white",
  "--secondary": "grayscale-130",
  "--secondary-foreground": "grayscale-10",
  "--muted": "grayscale-130",
  "--muted-foreground": "grayscale-70",
  "--accent": "brand-800",
  "--accent-foreground": "brand-100",
  "--destructive": "error-400",
  "--destructive-foreground": "white",
  "--success": "success-400",
  "--success-foreground": "white",
  "--warning": "warning-400",
  "--warning-foreground": "grayscale-140",
  "--info": "info-400",
  "--info-foreground": "white",
  "--border": "grayscale-110",
  "--input": "grayscale-110",
  "--disabled": "grayscale-120",
  "--disabled-foreground": "grayscale-70",
  "--disabled-border": "grayscale-110",
  "--ring": "brand-400",
  "--chart-1": "oklch(0.809 0.105 251.813)",
  "--chart-2": "oklch(0.623 0.214 259.815)",
  "--chart-3": "oklch(0.546 0.245 262.881)",
  "--chart-4": "oklch(0.488 0.243 264.376)",
  "--chart-5": "oklch(0.424 0.199 265.638)",
  "--sidebar": "grayscale-140",
  "--sidebar-foreground": "grayscale-10",
  "--sidebar-primary": "brand-500",
  "--sidebar-primary-foreground": "white",
  "--sidebar-accent": "brand-800",
  "--sidebar-accent-foreground": "brand-100",
  "--sidebar-border": "grayscale-110",
  "--sidebar-ring": "brand-400",
}

export function getSemanticTokenSource(
  variable: string,
  theme: "light" | "dark"
): string {
  const map = theme === "dark" ? DARK : LIGHT
  const source = map[variable]
  if (!source) return "—"
  return source
}
